;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        haskell-indentation-common-electric-command
        sp-backward-delete-char
        sp-delete-char
        sp-forward-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        org-end-of-line
        sp-backward-delete-char
        sp-forward-barf-sexp
        ))
