;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        ensime-company-complete-or-indent
        haskell-indentation-common-electric-command
        sp-backward-delete-char
        sp-delete-char
        sp-forward-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        ensime-mouse-motion
        org-end-of-line
        sp-backward-delete-char
        sp-forward-barf-sexp
        ))
