;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        ensime-company-complete-or-indent
        forward-sexp
        haskell-indentation-common-electric-command
        hydra-mark-modify/body
        hydra-mark-modify/mc/edit-beginnings-of-lines
        hydra-mark-modify/mc/edit-beginnings-of-lines-and-exit
        hydra-mark-modify/mc/edit-ends-of-lines
        hydra-mark-modify/mc/insert-numbers
        hydra-mark-modify/mc/mark-next-like-this
        hydra-mark-modify/mc/mark-next-like-this-symbol
        hydra-mark-modify/mc/mark-previous-like-this-and-exit
        hydra-mark-modify/mc/mark-previous-like-this-symbol
        hydra-mark-modify/mc/mark-previous-lines-and-exit
        hydra-mark-modify/nil
        hydra-mark-modify/noop-and-exit
        indent-for-tab-command
        kill-region-or-backward-kill-word
        org-beginning-of-line
        org-delete-char
        org-return
        org-self-insert-command
        sp-backward-delete-char
        sp-backward-sexp
        sp-backward-unwrap-sexp
        sp-delete-char
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-sexp
        sp-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        anzu-query-replace
        counsel-M-x
        ensime-mouse-motion
        flycheck-next-error
        hydra-mark-modify/er/mark-outside-quotes
        hydra-mark-modify/mc/edit-ends-of-lines
        hydra-mark-modify/mc/mark-next-like-this-and-exit
        hydra-mark-modify/mc/mark-next-lines
        hydra-mark-modify/mc/mark-next-lines-and-exit
        hydra-mark-modify/mc/mark-previous-like-this
        hydra-mark-modify/mc/mark-previous-lines
        iedit-switch-to-mc-mode
        mac-mwheel-scroll
        mark-sexp
        org-end-of-line
        sp-backward-delete-char
        sp-forward-barf-sexp
        ))
